### PR TITLE
Idc test wc

### PR DESCRIPTION
**Pull request by bcli4d**

### CODE REVIEW

**Comment by s-paquette** [comment]
@bcli4d Is this one still needed?

**Comment by bcli4d** [comment]
I don't know. I don't seem to be able to see IDC-Common issues.

**Comment by s-paquette** [comment]
@bcli4d It's not an issue, it's the PR you have into test. (Check under PRs.)

**Comment by bcli4d** [comment]
I've made some additional changes since then. So delete this one and I will
submit a new one?

**Comment by s-paquette** [comment]
@bcli4d This is a PR into test, not into master--if you have changes, they need to go into master first.

**Pull request merged**
